// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: proto/hr.proto

package hr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Employee models
type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,6,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	Role          string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	Level         int32                  `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	StartDate     string                 `protobuf:"bytes,10,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,11,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	ManagerId     string                 `protobuf:"bytes,12,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	DirectReports []string               `protobuf:"bytes,13,rep,name=direct_reports,json=directReports,proto3" json:"direct_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_proto_hr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Employee) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Employee) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Employee) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Employee) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Employee) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *Employee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Employee) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Employee) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Employee) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *Employee) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Employee) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *Employee) GetDirectReports() []string {
	if x != nil {
		return x.DirectReports
	}
	return nil
}

type EmployeeBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Level         int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,6,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	ManagerId     string                 `protobuf:"bytes,7,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeBrief) Reset() {
	*x = EmployeeBrief{}
	mi := &file_proto_hr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeBrief) ProtoMessage() {}

func (x *EmployeeBrief) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeBrief.ProtoReflect.Descriptor instead.
func (*EmployeeBrief) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{1}
}

func (x *EmployeeBrief) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EmployeeBrief) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *EmployeeBrief) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *EmployeeBrief) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *EmployeeBrief) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *EmployeeBrief) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *EmployeeBrief) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *EmployeeBrief) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Department models
type Department struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	ChildIds      []string               `protobuf:"bytes,4,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Department) Reset() {
	*x = Department{}
	mi := &file_proto_hr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Department) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Department) ProtoMessage() {}

func (x *Department) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Department.ProtoReflect.Descriptor instead.
func (*Department) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{2}
}

func (x *Department) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Department) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Department) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Department) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

func (x *Department) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DepartmentBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DepartmentBrief) Reset() {
	*x = DepartmentBrief{}
	mi := &file_proto_hr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepartmentBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepartmentBrief) ProtoMessage() {}

func (x *DepartmentBrief) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepartmentBrief.ProtoReflect.Descriptor instead.
func (*DepartmentBrief) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{3}
}

func (x *DepartmentBrief) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepartmentBrief) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Common messages
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_hr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{4}
}

// Employee Requests
type CreateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEmployeeRequest) Reset() {
	*x = CreateEmployeeRequest{}
	mi := &file_proto_hr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEmployeeRequest) ProtoMessage() {}

func (x *CreateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*CreateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEmployeeRequest) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_proto_hr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{6}
}

func (x *GetEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Employee      *Employee              `protobuf:"bytes,2,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmployeeRequest) Reset() {
	*x = UpdateEmployeeRequest{}
	mi := &file_proto_hr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmployeeRequest) ProtoMessage() {}

func (x *UpdateEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmployeeRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEmployeeRequest) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type DeleteEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEmployeeRequest) Reset() {
	*x = DeleteEmployeeRequest{}
	mi := &file_proto_hr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEmployeeRequest) ProtoMessage() {}

func (x *DeleteEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEmployeeRequest.ProtoReflect.Descriptor instead.
func (*DeleteEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEmployeeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SkipInactive  bool                   `protobuf:"varint,3,opt,name=skip_inactive,json=skipInactive,proto3" json:"skip_inactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesRequest) Reset() {
	*x = ListEmployeesRequest{}
	mi := &file_proto_hr_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesRequest) ProtoMessage() {}

func (x *ListEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesRequest.ProtoReflect.Descriptor instead.
func (*ListEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{9}
}

func (x *ListEmployeesRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListEmployeesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListEmployeesRequest) GetSkipInactive() bool {
	if x != nil {
		return x.SkipInactive
	}
	return false
}

type ListEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*EmployeeBrief       `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesResponse) Reset() {
	*x = ListEmployeesResponse{}
	mi := &file_proto_hr_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesResponse) ProtoMessage() {}

func (x *ListEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesResponse.ProtoReflect.Descriptor instead.
func (*ListEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{10}
}

func (x *ListEmployeesResponse) GetEmployees() []*EmployeeBrief {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *ListEmployeesResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

type GetDirectManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectManagerRequest) Reset() {
	*x = GetDirectManagerRequest{}
	mi := &file_proto_hr_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectManagerRequest) ProtoMessage() {}

func (x *GetDirectManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectManagerRequest.ProtoReflect.Descriptor instead.
func (*GetDirectManagerRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{11}
}

func (x *GetDirectManagerRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type SetManagerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManagerRequest) Reset() {
	*x = SetManagerRequest{}
	mi := &file_proto_hr_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManagerRequest) ProtoMessage() {}

func (x *SetManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManagerRequest.ProtoReflect.Descriptor instead.
func (*SetManagerRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{12}
}

func (x *SetManagerRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *SetManagerRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

type GetDirectReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmployeeId    string                 `protobuf:"bytes,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectReportsRequest) Reset() {
	*x = GetDirectReportsRequest{}
	mi := &file_proto_hr_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectReportsRequest) ProtoMessage() {}

func (x *GetDirectReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectReportsRequest.ProtoReflect.Descriptor instead.
func (*GetDirectReportsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{13}
}

func (x *GetDirectReportsRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type GetDirectReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectReports []string               `protobuf:"bytes,1,rep,name=direct_reports,json=directReports,proto3" json:"direct_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDirectReportsResponse) Reset() {
	*x = GetDirectReportsResponse{}
	mi := &file_proto_hr_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDirectReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDirectReportsResponse) ProtoMessage() {}

func (x *GetDirectReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDirectReportsResponse.ProtoReflect.Descriptor instead.
func (*GetDirectReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{14}
}

func (x *GetDirectReportsResponse) GetDirectReports() []string {
	if x != nil {
		return x.DirectReports
	}
	return nil
}

type AddDirectReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDirectReportRequest) Reset() {
	*x = AddDirectReportRequest{}
	mi := &file_proto_hr_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDirectReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDirectReportRequest) ProtoMessage() {}

func (x *AddDirectReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDirectReportRequest.ProtoReflect.Descriptor instead.
func (*AddDirectReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{15}
}

func (x *AddDirectReportRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *AddDirectReportRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type RemoveDirectReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	EmployeeId    string                 `protobuf:"bytes,2,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDirectReportRequest) Reset() {
	*x = RemoveDirectReportRequest{}
	mi := &file_proto_hr_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDirectReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDirectReportRequest) ProtoMessage() {}

func (x *RemoveDirectReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDirectReportRequest.ProtoReflect.Descriptor instead.
func (*RemoveDirectReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveDirectReportRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *RemoveDirectReportRequest) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

type GetEmployeeTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManagerId     string                 `protobuf:"bytes,1,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeTreeRequest) Reset() {
	*x = GetEmployeeTreeRequest{}
	mi := &file_proto_hr_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeTreeRequest) ProtoMessage() {}

func (x *GetEmployeeTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeTreeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{17}
}

func (x *GetEmployeeTreeRequest) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

type GetEmployeeTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DirectReports []string               `protobuf:"bytes,1,rep,name=direct_reports,json=directReports,proto3" json:"direct_reports,omitempty"` // 1-level only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeTreeResponse) Reset() {
	*x = GetEmployeeTreeResponse{}
	mi := &file_proto_hr_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeTreeResponse) ProtoMessage() {}

func (x *GetEmployeeTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeTreeResponse.ProtoReflect.Descriptor instead.
func (*GetEmployeeTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{18}
}

func (x *GetEmployeeTreeResponse) GetDirectReports() []string {
	if x != nil {
		return x.DirectReports
	}
	return nil
}

// Department Requests
type CreateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    *Department            `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepartmentRequest) Reset() {
	*x = CreateDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepartmentRequest) ProtoMessage() {}

func (x *CreateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*CreateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{19}
}

func (x *CreateDepartmentRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type GetDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentRequest) Reset() {
	*x = GetDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentRequest) ProtoMessage() {}

func (x *GetDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{20}
}

func (x *GetDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Department    *Department            `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDepartmentRequest) Reset() {
	*x = UpdateDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDepartmentRequest) ProtoMessage() {}

func (x *UpdateDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDepartmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDepartmentRequest) GetDepartment() *Department {
	if x != nil {
		return x.Department
	}
	return nil
}

type DeleteDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDepartmentRequest) Reset() {
	*x = DeleteDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDepartmentRequest) ProtoMessage() {}

func (x *DeleteDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDepartmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteDepartmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsRequest) Reset() {
	*x = ListDepartmentsRequest{}
	mi := &file_proto_hr_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsRequest) ProtoMessage() {}

func (x *ListDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*ListDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{23}
}

func (x *ListDepartmentsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ListDepartmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Departments   []*DepartmentBrief     `protobuf:"bytes,1,rep,name=departments,proto3" json:"departments,omitempty"`
	NextToken     string                 `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDepartmentsResponse) Reset() {
	*x = ListDepartmentsResponse{}
	mi := &file_proto_hr_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDepartmentsResponse) ProtoMessage() {}

func (x *ListDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*ListDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{24}
}

func (x *ListDepartmentsResponse) GetDepartments() []*DepartmentBrief {
	if x != nil {
		return x.Departments
	}
	return nil
}

func (x *ListDepartmentsResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

type GetParentDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetParentDepartmentRequest) Reset() {
	*x = GetParentDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetParentDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetParentDepartmentRequest) ProtoMessage() {}

func (x *GetParentDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetParentDepartmentRequest.ProtoReflect.Descriptor instead.
func (*GetParentDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{25}
}

func (x *GetParentDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type SetParentDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DepartmentId  string                 `protobuf:"bytes,1,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetParentDepartmentRequest) Reset() {
	*x = SetParentDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetParentDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetParentDepartmentRequest) ProtoMessage() {}

func (x *SetParentDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetParentDepartmentRequest.ProtoReflect.Descriptor instead.
func (*SetParentDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{26}
}

func (x *SetParentDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *SetParentDepartmentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type GetChildDepartmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChildDepartmentsRequest) Reset() {
	*x = GetChildDepartmentsRequest{}
	mi := &file_proto_hr_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildDepartmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildDepartmentsRequest) ProtoMessage() {}

func (x *GetChildDepartmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildDepartmentsRequest.ProtoReflect.Descriptor instead.
func (*GetChildDepartmentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{27}
}

func (x *GetChildDepartmentsRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type GetChildDepartmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildIds      []string               `protobuf:"bytes,1,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChildDepartmentsResponse) Reset() {
	*x = GetChildDepartmentsResponse{}
	mi := &file_proto_hr_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChildDepartmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChildDepartmentsResponse) ProtoMessage() {}

func (x *GetChildDepartmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChildDepartmentsResponse.ProtoReflect.Descriptor instead.
func (*GetChildDepartmentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{28}
}

func (x *GetChildDepartmentsResponse) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

type AddChildDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddChildDepartmentRequest) Reset() {
	*x = AddChildDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddChildDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddChildDepartmentRequest) ProtoMessage() {}

func (x *AddChildDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddChildDepartmentRequest.ProtoReflect.Descriptor instead.
func (*AddChildDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{29}
}

func (x *AddChildDepartmentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *AddChildDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type RemoveChildDepartmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	DepartmentId  string                 `protobuf:"bytes,2,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveChildDepartmentRequest) Reset() {
	*x = RemoveChildDepartmentRequest{}
	mi := &file_proto_hr_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveChildDepartmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveChildDepartmentRequest) ProtoMessage() {}

func (x *RemoveChildDepartmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveChildDepartmentRequest.ProtoReflect.Descriptor instead.
func (*RemoveChildDepartmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{30}
}

func (x *RemoveChildDepartmentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *RemoveChildDepartmentRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

type GetDepartmentTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentTreeRequest) Reset() {
	*x = GetDepartmentTreeRequest{}
	mi := &file_proto_hr_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentTreeRequest) ProtoMessage() {}

func (x *GetDepartmentTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentTreeRequest.ProtoReflect.Descriptor instead.
func (*GetDepartmentTreeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{31}
}

func (x *GetDepartmentTreeRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type GetDepartmentTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChildIds      []string               `protobuf:"bytes,1,rep,name=child_ids,json=childIds,proto3" json:"child_ids,omitempty"` // 1-level only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepartmentTreeResponse) Reset() {
	*x = GetDepartmentTreeResponse{}
	mi := &file_proto_hr_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepartmentTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepartmentTreeResponse) ProtoMessage() {}

func (x *GetDepartmentTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepartmentTreeResponse.ProtoReflect.Descriptor instead.
func (*GetDepartmentTreeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{32}
}

func (x *GetDepartmentTreeResponse) GetChildIds() []string {
	if x != nil {
		return x.ChildIds
	}
	return nil
}

var File_proto_hr_proto protoreflect.FileDescriptor

const file_proto_hr_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/hr.proto\x12\x02hr\"\xf6\x02\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x05 \x01(\tR\vphoneNumber\x12#\n" +
	"\rdepartment_id\x18\x06 \x01(\tR\fdepartmentId\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12\x14\n" +
	"\x05level\x18\b \x01(\x05R\x05level\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_date\x18\n" +
	" \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\v \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"manager_id\x18\f \x01(\tR\tmanagerId\x12%\n" +
	"\x0edirect_reports\x18\r \x03(\tR\rdirectReports\"\xe1\x01\n" +
	"\rEmployeeBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12#\n" +
	"\rdepartment_id\x18\x06 \x01(\tR\fdepartmentId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\a \x01(\tR\tmanagerId\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"\x8c\x01\n" +
	"\n" +
	"Department\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x1b\n" +
	"\tchild_ids\x18\x04 \x03(\tR\bchildIds\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"5\n" +
	"\x0fDepartmentBrief\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\a\n" +
	"\x05Empty\"A\n" +
	"\x15CreateEmployeeRequest\x12(\n" +
	"\bemployee\x18\x01 \x01(\v2\f.hr.EmployeeR\bemployee\"$\n" +
	"\x12GetEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x15UpdateEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\bemployee\x18\x02 \x01(\v2\f.hr.EmployeeR\bemployee\"'\n" +
	"\x15DeleteEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"g\n" +
	"\x14ListEmployeesRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12#\n" +
	"\rskip_inactive\x18\x03 \x01(\bR\fskipInactive\"g\n" +
	"\x15ListEmployeesResponse\x12/\n" +
	"\temployees\x18\x01 \x03(\v2\x11.hr.EmployeeBriefR\temployees\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\":\n" +
	"\x17GetDirectManagerRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\"S\n" +
	"\x11SetManagerRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\":\n" +
	"\x17GetDirectReportsRequest\x12\x1f\n" +
	"\vemployee_id\x18\x01 \x01(\tR\n" +
	"employeeId\"A\n" +
	"\x18GetDirectReportsResponse\x12%\n" +
	"\x0edirect_reports\x18\x01 \x03(\tR\rdirectReports\"X\n" +
	"\x16AddDirectReportRequest\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\tR\tmanagerId\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\"[\n" +
	"\x19RemoveDirectReportRequest\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\tR\tmanagerId\x12\x1f\n" +
	"\vemployee_id\x18\x02 \x01(\tR\n" +
	"employeeId\"7\n" +
	"\x16GetEmployeeTreeRequest\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x01 \x01(\tR\tmanagerId\"@\n" +
	"\x17GetEmployeeTreeResponse\x12%\n" +
	"\x0edirect_reports\x18\x01 \x03(\tR\rdirectReports\"I\n" +
	"\x17CreateDepartmentRequest\x12.\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x0e.hr.DepartmentR\n" +
	"department\"&\n" +
	"\x14GetDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Y\n" +
	"\x17UpdateDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\n" +
	"department\x18\x02 \x01(\v2\x0e.hr.DepartmentR\n" +
	"department\")\n" +
	"\x17DeleteDepartmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x16ListDepartmentsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"o\n" +
	"\x17ListDepartmentsResponse\x125\n" +
	"\vdepartments\x18\x01 \x03(\v2\x13.hr.DepartmentBriefR\vdepartments\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\"A\n" +
	"\x1aGetParentDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\"^\n" +
	"\x1aSetParentDepartmentRequest\x12#\n" +
	"\rdepartment_id\x18\x01 \x01(\tR\fdepartmentId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"9\n" +
	"\x1aGetChildDepartmentsRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\":\n" +
	"\x1bGetChildDepartmentsResponse\x12\x1b\n" +
	"\tchild_ids\x18\x01 \x03(\tR\bchildIds\"]\n" +
	"\x19AddChildDepartmentRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\"`\n" +
	"\x1cRemoveChildDepartmentRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12#\n" +
	"\rdepartment_id\x18\x02 \x01(\tR\fdepartmentId\"7\n" +
	"\x18GetDepartmentTreeRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\"8\n" +
	"\x19GetDepartmentTreeResponse\x12\x1b\n" +
	"\tchild_ids\x18\x01 \x03(\tR\bchildIds2\xbe\x05\n" +
	"\x0fEmployeeService\x129\n" +
	"\x0eCreateEmployee\x12\x19.hr.CreateEmployeeRequest\x1a\f.hr.Employee\x123\n" +
	"\vGetEmployee\x12\x16.hr.GetEmployeeRequest\x1a\f.hr.Employee\x129\n" +
	"\x0eUpdateEmployee\x12\x19.hr.UpdateEmployeeRequest\x1a\f.hr.Employee\x126\n" +
	"\x0eDeleteEmployee\x12\x19.hr.DeleteEmployeeRequest\x1a\t.hr.Empty\x12D\n" +
	"\rListEmployees\x12\x18.hr.ListEmployeesRequest\x1a\x19.hr.ListEmployeesResponse\x12=\n" +
	"\x10GetDirectManager\x12\x1b.hr.GetDirectManagerRequest\x1a\f.hr.Employee\x12.\n" +
	"\n" +
	"SetManager\x12\x15.hr.SetManagerRequest\x1a\t.hr.Empty\x12M\n" +
	"\x10GetDirectReports\x12\x1b.hr.GetDirectReportsRequest\x1a\x1c.hr.GetDirectReportsResponse\x128\n" +
	"\x0fAddDirectReport\x12\x1a.hr.AddDirectReportRequest\x1a\t.hr.Empty\x12>\n" +
	"\x12RemoveDirectReport\x12\x1d.hr.RemoveDirectReportRequest\x1a\t.hr.Empty\x12J\n" +
	"\x0fGetEmployeeTree\x12\x1a.hr.GetEmployeeTreeRequest\x1a\x1b.hr.GetEmployeeTreeResponse2\x91\x06\n" +
	"\x11DepartmentService\x12?\n" +
	"\x10CreateDepartment\x12\x1b.hr.CreateDepartmentRequest\x1a\x0e.hr.Department\x129\n" +
	"\rGetDepartment\x12\x18.hr.GetDepartmentRequest\x1a\x0e.hr.Department\x12?\n" +
	"\x10UpdateDepartment\x12\x1b.hr.UpdateDepartmentRequest\x1a\x0e.hr.Department\x12:\n" +
	"\x10DeleteDepartment\x12\x1b.hr.DeleteDepartmentRequest\x1a\t.hr.Empty\x12J\n" +
	"\x0fListDepartments\x12\x1a.hr.ListDepartmentsRequest\x1a\x1b.hr.ListDepartmentsResponse\x12E\n" +
	"\x13GetParentDepartment\x12\x1e.hr.GetParentDepartmentRequest\x1a\x0e.hr.Department\x12@\n" +
	"\x13SetParentDepartment\x12\x1e.hr.SetParentDepartmentRequest\x1a\t.hr.Empty\x12V\n" +
	"\x13GetChildDepartments\x12\x1e.hr.GetChildDepartmentsRequest\x1a\x1f.hr.GetChildDepartmentsResponse\x12>\n" +
	"\x12AddChildDepartment\x12\x1d.hr.AddChildDepartmentRequest\x1a\t.hr.Empty\x12D\n" +
	"\x15RemoveChildDepartment\x12 .hr.RemoveChildDepartmentRequest\x1a\t.hr.Empty\x12P\n" +
	"\x11GetDepartmentTree\x12\x1c.hr.GetDepartmentTreeRequest\x1a\x1d.hr.GetDepartmentTreeResponseB\x1fZ\x1dzhangbolong/OASIS-hr/proto;hrb\x06proto3"

var (
	file_proto_hr_proto_rawDescOnce sync.Once
	file_proto_hr_proto_rawDescData []byte
)

func file_proto_hr_proto_rawDescGZIP() []byte {
	file_proto_hr_proto_rawDescOnce.Do(func() {
		file_proto_hr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_proto_rawDesc), len(file_proto_hr_proto_rawDesc)))
	})
	return file_proto_hr_proto_rawDescData
}

var file_proto_hr_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_proto_hr_proto_goTypes = []any{
	(*Employee)(nil),                     // 0: hr.Employee
	(*EmployeeBrief)(nil),                // 1: hr.EmployeeBrief
	(*Department)(nil),                   // 2: hr.Department
	(*DepartmentBrief)(nil),              // 3: hr.DepartmentBrief
	(*Empty)(nil),                        // 4: hr.Empty
	(*CreateEmployeeRequest)(nil),        // 5: hr.CreateEmployeeRequest
	(*GetEmployeeRequest)(nil),           // 6: hr.GetEmployeeRequest
	(*UpdateEmployeeRequest)(nil),        // 7: hr.UpdateEmployeeRequest
	(*DeleteEmployeeRequest)(nil),        // 8: hr.DeleteEmployeeRequest
	(*ListEmployeesRequest)(nil),         // 9: hr.ListEmployeesRequest
	(*ListEmployeesResponse)(nil),        // 10: hr.ListEmployeesResponse
	(*GetDirectManagerRequest)(nil),      // 11: hr.GetDirectManagerRequest
	(*SetManagerRequest)(nil),            // 12: hr.SetManagerRequest
	(*GetDirectReportsRequest)(nil),      // 13: hr.GetDirectReportsRequest
	(*GetDirectReportsResponse)(nil),     // 14: hr.GetDirectReportsResponse
	(*AddDirectReportRequest)(nil),       // 15: hr.AddDirectReportRequest
	(*RemoveDirectReportRequest)(nil),    // 16: hr.RemoveDirectReportRequest
	(*GetEmployeeTreeRequest)(nil),       // 17: hr.GetEmployeeTreeRequest
	(*GetEmployeeTreeResponse)(nil),      // 18: hr.GetEmployeeTreeResponse
	(*CreateDepartmentRequest)(nil),      // 19: hr.CreateDepartmentRequest
	(*GetDepartmentRequest)(nil),         // 20: hr.GetDepartmentRequest
	(*UpdateDepartmentRequest)(nil),      // 21: hr.UpdateDepartmentRequest
	(*DeleteDepartmentRequest)(nil),      // 22: hr.DeleteDepartmentRequest
	(*ListDepartmentsRequest)(nil),       // 23: hr.ListDepartmentsRequest
	(*ListDepartmentsResponse)(nil),      // 24: hr.ListDepartmentsResponse
	(*GetParentDepartmentRequest)(nil),   // 25: hr.GetParentDepartmentRequest
	(*SetParentDepartmentRequest)(nil),   // 26: hr.SetParentDepartmentRequest
	(*GetChildDepartmentsRequest)(nil),   // 27: hr.GetChildDepartmentsRequest
	(*GetChildDepartmentsResponse)(nil),  // 28: hr.GetChildDepartmentsResponse
	(*AddChildDepartmentRequest)(nil),    // 29: hr.AddChildDepartmentRequest
	(*RemoveChildDepartmentRequest)(nil), // 30: hr.RemoveChildDepartmentRequest
	(*GetDepartmentTreeRequest)(nil),     // 31: hr.GetDepartmentTreeRequest
	(*GetDepartmentTreeResponse)(nil),    // 32: hr.GetDepartmentTreeResponse
}
var file_proto_hr_proto_depIdxs = []int32{
	0,  // 0: hr.CreateEmployeeRequest.employee:type_name -> hr.Employee
	0,  // 1: hr.UpdateEmployeeRequest.employee:type_name -> hr.Employee
	1,  // 2: hr.ListEmployeesResponse.employees:type_name -> hr.EmployeeBrief
	2,  // 3: hr.CreateDepartmentRequest.department:type_name -> hr.Department
	2,  // 4: hr.UpdateDepartmentRequest.department:type_name -> hr.Department
	3,  // 5: hr.ListDepartmentsResponse.departments:type_name -> hr.DepartmentBrief
	5,  // 6: hr.EmployeeService.CreateEmployee:input_type -> hr.CreateEmployeeRequest
	6,  // 7: hr.EmployeeService.GetEmployee:input_type -> hr.GetEmployeeRequest
	7,  // 8: hr.EmployeeService.UpdateEmployee:input_type -> hr.UpdateEmployeeRequest
	8,  // 9: hr.EmployeeService.DeleteEmployee:input_type -> hr.DeleteEmployeeRequest
	9,  // 10: hr.EmployeeService.ListEmployees:input_type -> hr.ListEmployeesRequest
	11, // 11: hr.EmployeeService.GetDirectManager:input_type -> hr.GetDirectManagerRequest
	12, // 12: hr.EmployeeService.SetManager:input_type -> hr.SetManagerRequest
	13, // 13: hr.EmployeeService.GetDirectReports:input_type -> hr.GetDirectReportsRequest
	15, // 14: hr.EmployeeService.AddDirectReport:input_type -> hr.AddDirectReportRequest
	16, // 15: hr.EmployeeService.RemoveDirectReport:input_type -> hr.RemoveDirectReportRequest
	17, // 16: hr.EmployeeService.GetEmployeeTree:input_type -> hr.GetEmployeeTreeRequest
	19, // 17: hr.DepartmentService.CreateDepartment:input_type -> hr.CreateDepartmentRequest
	20, // 18: hr.DepartmentService.GetDepartment:input_type -> hr.GetDepartmentRequest
	21, // 19: hr.DepartmentService.UpdateDepartment:input_type -> hr.UpdateDepartmentRequest
	22, // 20: hr.DepartmentService.DeleteDepartment:input_type -> hr.DeleteDepartmentRequest
	23, // 21: hr.DepartmentService.ListDepartments:input_type -> hr.ListDepartmentsRequest
	25, // 22: hr.DepartmentService.GetParentDepartment:input_type -> hr.GetParentDepartmentRequest
	26, // 23: hr.DepartmentService.SetParentDepartment:input_type -> hr.SetParentDepartmentRequest
	27, // 24: hr.DepartmentService.GetChildDepartments:input_type -> hr.GetChildDepartmentsRequest
	29, // 25: hr.DepartmentService.AddChildDepartment:input_type -> hr.AddChildDepartmentRequest
	30, // 26: hr.DepartmentService.RemoveChildDepartment:input_type -> hr.RemoveChildDepartmentRequest
	31, // 27: hr.DepartmentService.GetDepartmentTree:input_type -> hr.GetDepartmentTreeRequest
	0,  // 28: hr.EmployeeService.CreateEmployee:output_type -> hr.Employee
	0,  // 29: hr.EmployeeService.GetEmployee:output_type -> hr.Employee
	0,  // 30: hr.EmployeeService.UpdateEmployee:output_type -> hr.Employee
	4,  // 31: hr.EmployeeService.DeleteEmployee:output_type -> hr.Empty
	10, // 32: hr.EmployeeService.ListEmployees:output_type -> hr.ListEmployeesResponse
	0,  // 33: hr.EmployeeService.GetDirectManager:output_type -> hr.Employee
	4,  // 34: hr.EmployeeService.SetManager:output_type -> hr.Empty
	14, // 35: hr.EmployeeService.GetDirectReports:output_type -> hr.GetDirectReportsResponse
	4,  // 36: hr.EmployeeService.AddDirectReport:output_type -> hr.Empty
	4,  // 37: hr.EmployeeService.RemoveDirectReport:output_type -> hr.Empty
	18, // 38: hr.EmployeeService.GetEmployeeTree:output_type -> hr.GetEmployeeTreeResponse
	2,  // 39: hr.DepartmentService.CreateDepartment:output_type -> hr.Department
	2,  // 40: hr.DepartmentService.GetDepartment:output_type -> hr.Department
	2,  // 41: hr.DepartmentService.UpdateDepartment:output_type -> hr.Department
	4,  // 42: hr.DepartmentService.DeleteDepartment:output_type -> hr.Empty
	24, // 43: hr.DepartmentService.ListDepartments:output_type -> hr.ListDepartmentsResponse
	2,  // 44: hr.DepartmentService.GetParentDepartment:output_type -> hr.Department
	4,  // 45: hr.DepartmentService.SetParentDepartment:output_type -> hr.Empty
	28, // 46: hr.DepartmentService.GetChildDepartments:output_type -> hr.GetChildDepartmentsResponse
	4,  // 47: hr.DepartmentService.AddChildDepartment:output_type -> hr.Empty
	4,  // 48: hr.DepartmentService.RemoveChildDepartment:output_type -> hr.Empty
	32, // 49: hr.DepartmentService.GetDepartmentTree:output_type -> hr.GetDepartmentTreeResponse
	28, // [28:50] is the sub-list for method output_type
	6,  // [6:28] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_hr_proto_init() }
func file_proto_hr_proto_init() {
	if File_proto_hr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_proto_rawDesc), len(file_proto_hr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_hr_proto_goTypes,
		DependencyIndexes: file_proto_hr_proto_depIdxs,
		MessageInfos:      file_proto_hr_proto_msgTypes,
	}.Build()
	File_proto_hr_proto = out.File
	file_proto_hr_proto_goTypes = nil
	file_proto_hr_proto_depIdxs = nil
}
